### ISSUE TITLE
Conflicting definitions of method foo in Julia_for_Pythonistas.ipynb

### ISSUE THREAD

**Issue by ghost** [ageron/julia_notebooks#2]
At one point in the notebook there is: 
```julia
foo(x::Number) = "baz"
```
Later, there is this:
```julia
a = 1
foo(a=a+1, b=a) = println("a=$a, b=$b")
foo()
foo(5)
```
I'm running the notebook locally, and for the second block, the only output is "baz" (the println is not being called). I presume this is because the first definition of foo, having a more specific type, is getting in the way.

Thanks for the notebook -- it's very helpful.

**Comment by ageron** [comment]
Ah, thanks a lot for your feedback. Indeed, you are right, the first function is more specific. I must have restarted the runtime in between these two sections, my apologies, I'll fix that.
